### PR TITLE
dominant negative clinical significance icon switched to correct version

### PR DESCRIPTION
**Pull request by jmcmichael**

### CODE REVIEW

**Review by kkrysiak — COMMENTED** [review]
Wait, I thought this would be `resize-full` for DN? Maybe I'm looking at the wrong glyphicon set

**Comment by jmcmichael** [comment]
`resize-full` and `expand` are essentially the same icon in the different free icon sets "glyphicons" and "font-awesome". I'm not sure the provenance of those icon sets, but they're very similar. Confusingly, one can use both in sphinx/RST files, however I think the reason we're using the glyphicon extension for sphinx is b/c the `|icon-name|` notation works well in the RST table syntax while the font-awesome icons have to be displayed using HTML tags w/ style attributes which don't (and we use tables extensively for showing what various icons mean).

**Comment by malachig** [comment]
Okay, thanks for the explanation.

**Review by malachig — APPROVED** [review]
LGTM

**Pull request merged**
